# Generated by Django 6.0.4 on 2026-05-05 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_activity_date_activity_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='priority',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='scheduling_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLEXIBLE', 'Flexible'), ('FREE', 'Free'), ('OPTIONAL', 'Optional')], default='FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='competition',
            name='fighting_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PLANNED', 'Planned'), ('PAST', 'Past')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sub_type',
            field=models.CharField(blank=True, help_text='e.g. sauna, swimming, massage', max_length=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='rpe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
