# Generated by Django 6.0.4 on 2026-05-15 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduling_type', models.CharField(choices=[('FIXED', 'Fixed'), ('FLEXIBLE', 'Flexible'), ('FREE', 'Free'), ('OPTIONAL', 'Optional')], default='FIXED', max_length=20)),
                ('is_all_day', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='ONCE', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PLANNED', 'Planned'), ('PAST', 'Past')], default='PLANNED', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('fighting_weight', models.FloatField(blank=True, null=True)),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('recovery_type', models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive'), ('SOCIAL', 'Social')], max_length=20)),
                ('sub_type', models.CharField(blank=True, help_text='e.g. sauna, swimming, massage', max_length=100)),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('responsibility_type', models.CharField(choices=[('WORK', 'Work'), ('UNIVERSITY', 'University'), ('INTERNSHIP', 'Internship'), ('SCHOOL', 'School'), ('OTHERS', 'Others')], max_length=50)),
                ('movement', models.CharField(choices=[('SITTING', 'Sitting'), ('STANDING', 'Standing'), ('WALKING', 'Walking'), ('LIFTING', 'Lifting')], max_length=20)),
                ('rpe', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('training_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('SPARRING', 'Sparring'), ('PADS', 'Pads'), ('BAGWORK', 'Bagwork')], max_length=50)),
                ('intensity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('rpe', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(blank=True, choices=[('BOXING', 'Boxing'), ('MMA', 'MMA'), ('THAIBOXING', 'Thai Boxing')], max_length=50, null=True)),
                ('chronical_disease', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INJURED', 'Injured'), ('RECOVERY', 'Recovery')], default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.profile'),
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.FloatField()),
                ('mood', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('current_weight', models.FloatField()),
                ('energy', models.CharField(choices=[('HIGH', 'High'), ('MIDDLE', 'Middle'), ('LOW', 'Low')], max_length=10)),
                ('menstrual_cycle', models.CharField(blank=True, choices=[('MENSTRUATION', 'Menstruation'), ('FOLLICULAR', 'Follicular'), ('OVULATION', 'Ovulation'), ('LUTEAL', 'Luteal')], max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='activities.profile')),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
