# Generated by Django 6.0.4 on 2026-05-17 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2026-01-01', help_text='Datum der Ausführung oder der ersten Ausführung bei Wiederholungen.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='ONCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='recovery_type',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive'), ('SOCIAL', 'Social')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sub_type',
            field=models.CharField(blank=True, help_text='e.g. sauna, swimming, massage', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='movement',
            field=models.CharField(blank=True, choices=[('SITTING', 'Sitting'), ('STANDING', 'Standing'), ('WALKING', 'Walking'), ('LIFTING', 'Lifting')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='responsibility_type',
            field=models.CharField(blank=True, choices=[('WORK', 'Work'), ('UNIVERSITY', 'University'), ('INTERNSHIP', 'Internship'), ('SCHOOL', 'School'), ('OTHERS', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='rpe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='training',
            name='intensity',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(blank=True, choices=[('TECHNICAL', 'Technical'), ('SPARRING', 'Sparring'), ('PADS', 'Pads'), ('BAGWORK', 'Bagwork')], max_length=50, null=True),
        ),
    ]
