# Generated by Django 6.0.4 on 2026-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_otheractivity_alter_activity_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, help_text='Pflicht bei ONCE. Startdatum bei DAILY/WEEKLY (optional, Standard ist heute).', null=True),
        ),
    ]
