# Generated by Django 6.0.4 on 2026-05-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_date_alter_activity_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('notes', models.TextField(blank=True, help_text='Any details about this activity', null=True)),
            ],
            bases=('activities.activity',),
        ),
    ]
