# Generated by Django 6.0.4 on 2026-06-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=60, help_text='Geplante Dauer der Aktivität in Minuten.'),
        ),
        migrations.CreateModel(
            name='FlexibleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Gilt für einmalige Optionen', null=True)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Gilt für wöchentliche Optionen', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_slots', to='activities.activity')),
            ],
        ),
    ]
