# Generated by Django 6.0.4 on 2026-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_duration_flexibleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=2),
        ),
    ]
